# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
        colors = true
        interval = 5
	separator = ""
	output_format = "i3bar"
    	color_good = "#6E5AD6"
    	color_degraded = "#4A4654"
    	color_bad = "#D38C26"
}

#order += "ipv4"
#order += "disk /"


order += "volume master"
order += "wireless _first_"
order += "ethernet _first_"
order += "tztime local"

order += "battery 0"
order += "battery 1"
order += "cpu_temperature 0"
order += "load"
order += "memory"

wireless _first_ {
        format_up = "[ ON]"
        format_down = ":: ::"
}

ethernet _first_ {
        format_up = "[󰈀 ON]"
        format_down = "::󰈀 ::"
}

battery 0 {
        format = "[0 %status %percentage]"
	last_full_capacity = "true"
        status_chr = " "
        status_bat = ""
	status_full = ""
		
}

battery 1 {

	format = "[1 %status %percentage]"
	last_full_capacity = "true"
        status_chr = ""
        status_bat = ""
	status_full = ""

}
volume master {
        format = "[ %volume]"
	format_muted = ":: ::"

}

disk "/" {
        format = ""
}

load {
        format = "[ %1min]"
	
}

memory {
        format = "[󰘚 %used]"
        threshold_degraded = "1G"
        format_degraded = "MEMORY < %available"
}

tztime local {
        format = "[%D|%H:%M]"
}

cpu_temperature 0 {
    format = "[ %degrees°C]"
    path = "/sys/class/thermal/thermal_zone0/temp"
    max_threshold = 75
}
